apiVersion: v1
kind: Service
metadata:
  name: {{ template "template.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ index .Values "engagement-layer" "port" }}
      targetPort: 4180
  selector: {{- include "template.matchLabels" . | nindent 4 }}
